# config.yml
local_backend: true

backend:
  name: git-gateway
  repo: cnoss/thesis
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'

collections:
  - name: 'research-questions'
    label: 'Proposals'
    folder: '_research-questions'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'work' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'datum', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["proposal", "in-progress", "finished", "unpublished"]
      - label: "Keywords"
        name: "keywords"
        widget: "list"
        allow_add: true
        default: ["Design"]
  - name: 'works'
    label: 'Arbeiten'
    folder: '_works'
    create: true
    slug: "{{author}}-{{slug}}-{{date}}"
    summary: "{{author}}: {{title}} // {{type}}"
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'work-result' }
      - { label: 'Autor*in', name: 'author', widget: 'string' }
      - { label: 'Zugeh√∂riger Ordner', name: 'related-folder', widget: 'string', required: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - label: 'Datum'
        name: date
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        format: "LLL"
        picker_utc: true
        required: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Ergebnis als PDF"
        name: "result-pdf"
        widget: "file"
        required: false
        media_folder: 'uploads'
        media_library:
          config:
            multiple: true
      - { label: 'URL zur Website', name: 'result-website', widget: 'string', required: false }
      - { label: 'URL zum Repo', name: 'result-repo', widget: 'string', required: false }
      - { label: 'Slideshow', name: 'slideshow', widget: 'boolean', default: false, required: false }    
      - { label: 'YouTube ID vom Abschlussvideo', name: 'final-presentation', widget: 'string', required: false }
      - { label: 'Research Diary', name: 'research-diary', widget: 'boolean', default: false, required: false }
      - label: "Typ"
        name: "type"
        widget: "select"
        options: ["Praxisprojekt", "Bachelorarbeit", "Masterarbeit"]
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["in Bearbeitung", "Published", "Unpublished"]
      - label: "Keywords"
        name: "keywords"
        widget: "string"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        required: false
        choose_url: true 
      - label: "Avatar Image"
        name: "avatar"
        widget: "image"
        required: false
        choose_url: true         
      - { label: 'Kooperationspartner', name: 'partner', widget: 'string', required: false }
      - { label: 'Kooperationspartner Website', name: 'partner-url', widget: 'string',required: false }
      
